inputs:
  name:
    description: "name of the cache"
    required: true

outputs:
  cache-hit:
    description: "whether the cache was hit"
    value: ${{ steps.cache.outputs.cache-hit }}

runs:
  using: "composite"
  steps:
    - uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      id: cache
      with:
        path: "/tmp/${{ inputs.name }}.nario"
        key: "nix-init-${{ inputs.name }}-${{ hashFiles('**/flake.lock') }}"

    - if: ${{ steps.cache.outputs.cache-hit == 'true' }}
      shell: bash
      run: nix nario import --no-check-sigs < "/tmp/${{ inputs.name }}.nario"
